filename: ci/cloudbuild/cloudbuild.yaml
github:
  name: google-cloud-cpp
  owner: googleapis
  pullRequest:
    branch: ^(master|main|v\d+\..*)$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
name: cmake-gcs-rest-install-pr
substitutions:
  _BUILD_NAME: cmake-gcs-rest-install
  _DISTRO: fedora-35
  _TRIGGER_TYPE: pr
tags:
- pr
